version: '3.7'
services:
    factorio:
        image: pavolab/factorio:0.16
        container_name: factorio
        ports:
        - "34197:34197/udp"
        - "27015:27015/tcp"
        volumes:
        - /opt/factorio:/factorio
        restart: always
        networks:
            - net-pavo
        
networks: 
    net-pavo: